# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x:\UNCuyo\Por Cursar\POO\Poo_libre\client\view\ui\inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(500, 450)
        Inicio.setMinimumSize(QtCore.QSize(500, 300))
        Inicio.setMaximumSize(QtCore.QSize(1024, 786))
        Inicio.setStyleSheet("background-color: rgb(7, 52, 255);\n"
"\n"
"")
        self.verticalLayoutWidget = QtWidgets.QWidget(Inicio)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 415, 426))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.titulo.setMinimumSize(QtCore.QSize(400, 100))
        self.titulo.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(24)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_2.addWidget(self.titulo)
        self.Imagen = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Imagen.setMinimumSize(QtCore.QSize(350, 200))
        self.Imagen.setMaximumSize(QtCore.QSize(350, 200))
        self.Imagen.setStyleSheet("border: 5px solid black;")
        self.Imagen.setText("")
        self.Imagen.setPixmap(QtGui.QPixmap("x:\\UNCuyo\\Por Cursar\\POO\\Poo_libre\\client\\view\\ui\\../../../../on_linux/poo_libre/imagenes/tank000.png"))
        self.Imagen.setScaledContents(True)
        self.Imagen.setAlignment(QtCore.Qt.AlignCenter)
        self.Imagen.setObjectName("Imagen")
        self.verticalLayout_2.addWidget(self.Imagen, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_password = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_password.setMinimumSize(QtCore.QSize(100, 20))
        self.lb_password.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.lb_password.setFont(font)
        self.lb_password.setObjectName("lb_password")
        self.verticalLayout_3.addWidget(self.lb_password)
        self.lb_usuario = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_usuario.setMinimumSize(QtCore.QSize(100, 20))
        self.lb_usuario.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.lb_usuario.setFont(font)
        self.lb_usuario.setObjectName("lb_usuario")
        self.verticalLayout_3.addWidget(self.lb_usuario)
        self.btn_registrar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_registrar.setStyleSheet("background-color: rgb(178, 55, 255);")
        self.btn_registrar.setObjectName("btn_registrar")
        self.verticalLayout_3.addWidget(self.btn_registrar)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.le_usuario = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_usuario.setMinimumSize(QtCore.QSize(300, 20))
        self.le_usuario.setMaximumSize(QtCore.QSize(350, 20))
        self.le_usuario.setObjectName("le_usuario")
        self.verticalLayout_5.addWidget(self.le_usuario)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.btn_ingresar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_ingresar.setStyleSheet("background-color: rgb(178, 55, 255);")
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.verticalLayout_5.addWidget(self.btn_ingresar)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "Form"))
        self.titulo.setText(_translate("Inicio", "    Inicio de sesión"))
        self.lb_password.setText(_translate("Inicio", "Contraseña:"))
        self.lb_usuario.setText(_translate("Inicio", "Usuario:"))
        self.btn_registrar.setText(_translate("Inicio", "registrar"))
        self.btn_ingresar.setText(_translate("Inicio", "Ingresar"))
